### ISSUE TITLE
Incompatible with Optifine b1.8.1 ?

### ISSUE THREAD

**Issue by lemmings189** [BlueStaggo/Beta1.8.X#1]
Hi,
just tried optifine standard, smooth and multi-thread vb1.8.1, crashes when launching a world, or when going in deeper video parameters.

**Comment by lemmings189** [comment]
wait a minute;.. I cannot go to the video settings rn, white screen, even when removing optifine and resetting the mod (minecraft b1.8.X)
java.lang.ArrayIndexOutOfBoundsException: 3
	at fv.c(SourceFile:280)
	at ho.a(GuiVideoSettings.java:24)
	at qr.a(GuiScreen.java:84)
	at net.minecraft.client.Minecraft.a(Minecraft.java:351)
	at bj.a(GuiOptions.java:46)
	at qr.a(GuiScreen.java:59)
	at qr.f(GuiScreen.java:107)
	at qr.i(GuiScreen.java:92)
	at net.minecraft.client.Minecraft.k(Minecraft.java:898)
	at net.minecraft.client.Minecraft.run(Minecraft.java:463)
	at java.lang.Thread.run(Unknown Source)
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

**Comment by lemmings189** [comment]
I think Optifine just broke my game. I reinstalled it with only Mc b1.8.X and it runs well
